#version: '3.8'

services:
  api:
    build: .
    ports:
      - 8080:8080
    restart: on-failure:10
    environment:
      - PORT=8080
      - DATABASE_URL=db
    depends_on:
      - db
#        codition: service_healthy
  db:
    image: postgres
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    #command: bash -c "setup_database.sh"
volumes:
  pgdata:
